# Generated by Django 3.2.7 on 2023-01-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20230107_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='attendance',
            field=models.DateTimeField(),
        ),
    ]
