# Generated by Django 3.2.7 on 2023-01-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_booking_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.TextField(max_length=200),
        ),
    ]
