# Generated by Django 3.2.7 on 2023-01-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.TextField(max_length=200),
        ),
    ]
