# Generated by Django 3.2.7 on 2023-01-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20230108_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
        migrations.AddField(
            model_name='room',
            name='secret_key',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
